<?php

return [
    'name' => 'XCodrix',
    'domain' => 'https://xcodrix.com',
    'email' => 'hello@xcodrix.com',
    'tagline' => 'Premium Software Development Agency',

    'social' => [
        'linkedin' => 'https://linkedin.com/company/xcodrix',
        'twitter' => 'https://twitter.com/xcodrix',
        'github' => 'https://github.com/xcodrix',
    ],

    'stats' => [
        ['value' => '150+', 'label' => 'Projects Delivered'],
        ['value' => '85+', 'label' => 'Happy Clients'],
        ['value' => '12+', 'label' => 'Years Experience'],
        ['value' => '98%', 'label' => 'Client Retention'],
    ],

    'clients' => [
        'TechVenture', 'CloudScale', 'DataFlow', 'InnovateLab',
        'NextGen SaaS', 'VoiceConnect', 'FinEdge', 'HealthStack',
    ],

    'services' => [
        [
            'slug' => 'ai-development',
            'title' => 'AI Development',
            'icon' => 'ai',
            'popular' => true,
            'summary' => 'Custom AI solutions including LLM integrations, intelligent automation, and machine learning pipelines.',
            'what' => 'XCodrix builds production-ready AI systems — from chatbots and document intelligence to predictive analytics and workflow automation powered by OpenAI, Claude, and custom models.',
            'benefits' => ['Automate repetitive tasks and reduce operational costs', 'Deliver personalized user experiences at scale', 'Gain actionable insights from your business data', 'Stay competitive with cutting-edge AI capabilities'],
            'technologies' => ['OpenAI', 'Claude API', 'Python', 'LangChain', 'TensorFlow', 'Pinecone'],
            'why' => 'We bridge the gap between AI research and real business outcomes, shipping reliable AI features that integrate seamlessly with your existing products.',
        ],
        [
            'slug' => 'saas-development',
            'title' => 'SaaS Development',
            'icon' => 'saas',
            'popular' => true,
            'summary' => 'End-to-end SaaS platforms with subscription billing, multi-tenancy, and scalable cloud architecture.',
            'what' => 'We design and build complete SaaS products — from MVP to enterprise scale — including user management, billing, dashboards, and analytics.',
            'benefits' => ['Launch faster with proven SaaS architecture patterns', 'Built-in subscription and payment integrations', 'Scalable multi-tenant infrastructure', 'Recurring revenue-ready from day one'],
            'technologies' => ['Laravel', 'Vue.js', 'Stripe', 'PostgreSQL', 'Redis', 'AWS'],
            'why' => 'XCodrix has shipped multiple SaaS products and understands the nuances of billing, onboarding, and retention-focused UX.',
        ],
        [
            'slug' => 'custom-software-development',
            'title' => 'Custom Software Development',
            'icon' => 'code',
            'popular' => false,
            'summary' => 'Tailored software solutions built around your unique business processes and growth goals.',
            'what' => 'When off-the-shelf tools fall short, XCodrix builds bespoke applications that fit your exact workflow, compliance needs, and integration requirements.',
            'benefits' => ['Software that matches your business, not the other way around', 'Eliminate tool sprawl and manual workarounds', 'Full ownership of your intellectual property', 'Designed for long-term maintainability'],
            'technologies' => ['Laravel', 'PHP', 'Vue.js', 'MySQL', 'Docker', 'REST APIs'],
            'why' => 'We take time to understand your business before writing code, ensuring every feature drives measurable value.',
        ],
        [
            'slug' => 'laravel-development',
            'title' => 'Laravel Development',
            'icon' => 'laravel',
            'popular' => true,
            'summary' => 'Expert Laravel backends — APIs, admin panels, queues, and enterprise-grade PHP applications.',
            'what' => 'XCodrix specializes in Laravel, building robust backends with clean architecture, comprehensive testing, and optimized database design.',
            'benefits' => ['Rapid development with Laravel\'s elegant ecosystem', 'Secure, well-tested code following best practices', 'Seamless API and frontend integration', 'Easy to scale and maintain over time'],
            'technologies' => ['Laravel 11+', 'PHP 8.4', 'MySQL', 'PostgreSQL', 'Redis', 'Horizon'],
            'why' => 'Laravel is our core expertise. We contribute to the ecosystem and follow the latest framework conventions and performance patterns.',
        ],
        [
            'slug' => 'php-development',
            'title' => 'PHP Development',
            'icon' => 'php',
            'popular' => false,
            'summary' => 'Modern PHP development for web applications, APIs, and legacy system modernization.',
            'what' => 'From greenfield PHP projects to modernizing legacy codebases, XCodrix delivers clean, performant PHP solutions using modern standards.',
            'benefits' => ['Cost-effective development with a mature ecosystem', 'Modernize legacy systems without full rewrites', 'High-performance server-side applications', 'Extensive library and hosting support'],
            'technologies' => ['PHP 8.4', 'Laravel', 'Composer', 'PHPUnit', 'Nginx', 'MySQL'],
            'why' => 'Our team has deep PHP expertise spanning 12+ years, with a focus on modern patterns and security.',
        ],
        [
            'slug' => 'vuejs-development',
            'title' => 'Vue.js Development',
            'icon' => 'vue',
            'popular' => false,
            'summary' => 'Reactive, component-driven frontends with Vue.js for fast, interactive user experiences.',
            'what' => 'We build polished Vue.js applications — SPAs, dashboards, and embedded widgets — with Pinia state management and TypeScript.',
            'benefits' => ['Lightning-fast, reactive user interfaces', 'Component reusability across your product', 'Smooth integration with Laravel APIs', 'Excellent developer experience and maintainability'],
            'technologies' => ['Vue 3', 'Pinia', 'TypeScript', 'Vite', 'Tailwind CSS', 'Vitest'],
            'why' => 'Vue.js pairs perfectly with Laravel, and our full-stack team delivers cohesive frontend-backend solutions.',
        ],
        [
            'slug' => 'nuxtjs-development',
            'title' => 'Nuxt.js Development',
            'icon' => 'nuxt',
            'popular' => false,
            'summary' => 'SEO-friendly Vue applications with server-side rendering, static generation, and optimal performance.',
            'what' => 'XCodrix builds Nuxt.js applications that rank well on Google while delivering rich, app-like experiences with SSR and SSG.',
            'benefits' => ['Superior SEO with server-side rendering', 'Faster page loads and better Core Web Vitals', 'Automatic code splitting and optimization', 'Flexible deployment options'],
            'technologies' => ['Nuxt 3', 'Vue 3', 'TypeScript', 'Tailwind CSS', 'Vercel', 'Node.js'],
            'why' => 'We understand when SSR matters for SEO and performance, and Nuxt is our go-to for content-heavy and marketing sites.',
        ],
        [
            'slug' => 'twilio-voice-sms',
            'title' => 'Twilio Voice & SMS Solutions',
            'icon' => 'twilio',
            'popular' => true,
            'summary' => 'Voice calling, SMS, IVR systems, and communication workflows powered by Twilio.',
            'what' => 'We build Twilio-powered communication systems — call centers, appointment reminders, two-factor auth, IVR menus, and webhook-driven voice bots.',
            'benefits' => ['Reach customers via voice and SMS at scale', 'Automate call routing and customer support', 'Integrate communications into your CRM or app', 'Reliable, global telephony infrastructure'],
            'technologies' => ['Twilio Voice', 'Twilio SMS', 'TwiML', 'Laravel', 'WebSockets', 'Redis'],
            'why' => 'XCodrix has extensive Twilio integration experience, building production voice and SMS systems for healthcare, logistics, and SaaS clients.',
        ],
        [
            'slug' => 'crm-development',
            'title' => 'CRM Development',
            'icon' => 'crm',
            'popular' => false,
            'summary' => 'Custom CRM systems tailored to your sales pipeline, customer data, and team workflows.',
            'what' => 'We build CRM platforms that match how your team actually works — lead tracking, pipeline management, automation, and reporting.',
            'benefits' => ['CRM built for your process, not generic templates', 'Integrate with your existing tools and data sources', 'Automate follow-ups and reduce manual data entry', 'Real-time dashboards for sales and management'],
            'technologies' => ['Laravel', 'Vue.js', 'PostgreSQL', 'Redis', 'Twilio', 'REST APIs'],
            'why' => 'Off-the-shelf CRMs often create friction. We build systems your team will actually use every day.',
        ],
        [
            'slug' => 'api-development',
            'title' => 'API Development',
            'icon' => 'api',
            'popular' => false,
            'summary' => 'RESTful and GraphQL APIs with authentication, documentation, and third-party integrations.',
            'what' => 'XCodrix designs and builds APIs that power mobile apps, partner integrations, and microservices with clear documentation and versioning.',
            'benefits' => ['Enable mobile apps and third-party integrations', 'Clean, versioned APIs with comprehensive docs', 'Secure authentication and rate limiting', 'Scalable architecture for growing traffic'],
            'technologies' => ['Laravel', 'OpenAPI', 'OAuth 2.0', 'GraphQL', 'Postman', 'Redis'],
            'why' => 'Well-designed APIs are the backbone of modern software. We prioritize consistency, security, and developer experience.',
        ],
        [
            'slug' => 'cloud-devops',
            'title' => 'Cloud & DevOps',
            'icon' => 'cloud',
            'popular' => false,
            'summary' => 'Cloud infrastructure, CI/CD pipelines, containerization, and monitoring for reliable deployments.',
            'what' => 'We set up and manage cloud infrastructure on AWS, GCP, and DigitalOcean — Docker, Kubernetes, automated deployments, and observability.',
            'benefits' => ['Reliable, automated deployments with zero-downtime', 'Scalable infrastructure that grows with your users', 'Reduced ops overhead with CI/CD pipelines', 'Proactive monitoring and incident response'],
            'technologies' => ['AWS', 'Docker', 'GitHub Actions', 'Nginx', 'Terraform', 'Datadog'],
            'why' => 'DevOps is integrated into our development process from day one, not bolted on after launch.',
        ],
        [
            'slug' => 'ui-ux-design',
            'title' => 'UI/UX Design',
            'icon' => 'design',
            'popular' => false,
            'summary' => 'User-centered design for web and mobile — wireframes, prototypes, and design systems.',
            'what' => 'Our design team creates intuitive interfaces that convert visitors into customers, with user research, wireframing, and high-fidelity prototypes.',
            'benefits' => ['Higher conversion rates with user-centered design', 'Consistent brand experience across all touchpoints', 'Reduce development rework with clear prototypes', 'Accessible designs that work for everyone'],
            'technologies' => ['Figma', 'Tailwind CSS', 'Design Systems', 'Prototyping', 'User Research', 'A/B Testing'],
            'why' => 'Design and development under one roof means faster iteration and pixel-perfect implementation.',
        ],
        [
            'slug' => 'mobile-app-development',
            'title' => 'Mobile App Development',
            'icon' => 'mobile',
            'popular' => false,
            'summary' => 'Native and cross-platform mobile apps for iOS and Android with seamless backend integration.',
            'what' => 'XCodrix builds mobile applications using React Native and Flutter, integrated with Laravel APIs for a complete mobile experience.',
            'benefits' => ['Reach customers on iOS and Android', 'Cross-platform development reduces time and cost', 'Offline-capable apps with sync', 'Push notifications and in-app messaging'],
            'technologies' => ['React Native', 'Flutter', 'Laravel API', 'Firebase', 'App Store', 'Google Play'],
            'why' => 'Our full-stack approach means your mobile app and backend are built together, not by separate teams.',
        ],
    ],

    'why_choose_us' => [
        ['title' => 'Expert Engineering Team', 'description' => 'Senior developers with 12+ years of experience across Laravel, Vue.js, AI, and cloud infrastructure.', 'icon' => 'team'],
        ['title' => 'Transparent Process', 'description' => 'Weekly demos, clear timelines, and direct communication. You always know where your project stands.', 'icon' => 'process'],
        ['title' => 'On-Time Delivery', 'description' => 'We commit to realistic deadlines and deliver. 98% of our projects ship on or ahead of schedule.', 'icon' => 'delivery'],
        ['title' => 'Scalable Architecture', 'description' => 'Every system we build is designed to grow — from MVP to millions of users without rewrites.', 'icon' => 'scale'],
        ['title' => 'Full-Stack Capability', 'description' => 'Backend, frontend, mobile, DevOps, and AI under one roof. No coordination headaches.', 'icon' => 'stack'],
        ['title' => 'Long-Term Partnership', 'description' => 'We don\'t disappear after launch. Ongoing support, maintenance, and feature development.', 'icon' => 'partnership'],
    ],

    'process' => [
        ['step' => '01', 'title' => 'Discovery & Strategy', 'description' => 'We learn your business goals, users, and technical requirements. You receive a detailed project proposal within 48 hours.'],
        ['step' => '02', 'title' => 'Design & Prototyping', 'description' => 'Wireframes and interactive prototypes align the team on UX before a single line of code is written.'],
        ['step' => '03', 'title' => 'Agile Development', 'description' => 'Two-week sprints with weekly demos. You see progress continuously and can adjust priorities in real time.'],
        ['step' => '04', 'title' => 'Testing & QA', 'description' => 'Automated tests, manual QA, performance audits, and security reviews before every release.'],
        ['step' => '05', 'title' => 'Launch & Deployment', 'description' => 'Zero-downtime deployment to production with monitoring, documentation, and team training.'],
        ['step' => '06', 'title' => 'Support & Growth', 'description' => 'Post-launch maintenance, feature iterations, and scaling support as your product grows.'],
    ],

    'industries' => [
        ['name' => 'SaaS & Startups', 'description' => 'MVPs, subscription platforms, and growth-stage product development for SaaS companies.', 'icon' => 'saas'],
        ['name' => 'Healthcare', 'description' => 'HIPAA-aware patient portals, telehealth platforms, and medical practice management systems.', 'icon' => 'health'],
        ['name' => 'FinTech', 'description' => 'Payment processing, financial dashboards, and secure transaction systems.', 'icon' => 'fintech'],
        ['name' => 'E-Commerce', 'description' => 'Custom storefronts, inventory management, and marketplace platforms.', 'icon' => 'ecommerce'],
        ['name' => 'Real Estate', 'description' => 'Property listing platforms, CRM for agents, and virtual tour integrations.', 'icon' => 'realestate'],
        ['name' => 'Education', 'description' => 'Learning management systems, student portals, and EdTech platforms.', 'icon' => 'education'],
        ['name' => 'Logistics', 'description' => 'Fleet tracking, route optimization, and supply chain management tools.', 'icon' => 'logistics'],
        ['name' => 'Telecommunications', 'description' => 'Twilio-powered voice systems, call centers, and SMS notification platforms.', 'icon' => 'telecom'],
    ],

    'technologies' => [
        'Backend' => ['Laravel', 'PHP', 'Node.js', 'Python', 'REST APIs', 'GraphQL'],
        'Frontend' => ['Vue.js', 'Nuxt.js', 'React', 'TypeScript', 'Tailwind CSS', 'Alpine.js'],
        'Mobile' => ['React Native', 'Flutter', 'iOS', 'Android'],
        'Database' => ['MySQL', 'PostgreSQL', 'Redis', 'MongoDB', 'SQLite'],
        'Cloud & DevOps' => ['AWS', 'GCP', 'Docker', 'Kubernetes', 'GitHub Actions', 'Nginx'],
        'Integrations' => ['Twilio', 'Stripe', 'OpenAI', 'Claude', 'SendGrid', 'Firebase'],
    ],

    'portfolio' => [
        ['title' => 'SaaS Analytics Platform', 'category' => 'SaaS Development', 'image' => 'portfolio-1.webp', 'description' => 'Real-time analytics dashboard for a B2B SaaS company serving 5,000+ users.'],
        ['title' => 'Healthcare Telehealth App', 'category' => 'Mobile + Laravel', 'image' => 'portfolio-2.webp', 'description' => 'HIPAA-compliant telehealth platform with video calls and patient records.'],
        ['title' => 'AI Customer Support Bot', 'category' => 'AI Development', 'image' => 'portfolio-3.webp', 'description' => 'LLM-powered support bot reducing ticket volume by 60% for an e-commerce brand.'],
        ['title' => 'FinTech Payment Gateway', 'category' => 'API Development', 'image' => 'portfolio-4.webp', 'description' => 'Secure payment processing API handling $2M+ monthly transactions.'],
        ['title' => 'CRM for Real Estate', 'category' => 'CRM Development', 'image' => 'portfolio-5.webp', 'description' => 'Custom CRM with lead scoring, pipeline automation, and Twilio integration.'],
        ['title' => 'Voice IVR System', 'category' => 'Twilio Solutions', 'image' => 'portfolio-6.webp', 'description' => 'Automated call routing and appointment booking via Twilio Voice.'],
        ['title' => 'E-Commerce Marketplace', 'category' => 'Web Development', 'image' => 'portfolio-7.webp', 'description' => 'Multi-vendor marketplace with Stripe Connect and real-time inventory.'],
        ['title' => 'EdTech Learning Platform', 'category' => 'SaaS Development', 'image' => 'portfolio-8.webp', 'description' => 'LMS with course builder, quizzes, and progress tracking for 10,000 students.'],
        ['title' => 'Logistics Fleet Tracker', 'category' => 'Custom Software', 'image' => 'portfolio-9.webp', 'description' => 'GPS fleet tracking with route optimization and driver mobile app.'],
    ],

    'testimonials' => [
        ['name' => 'Sarah Wilson', 'role' => 'CEO, TechVenture', 'image' => 'sara-wilsone.webp', 'text' => 'XCodrix transformed our idea into a production SaaS platform in 4 months. Their Laravel expertise and transparent process made the entire experience seamless.'],
        ['name' => 'Matt Brandon', 'role' => 'CTO, CloudScale', 'image' => 'matt-brandon.webp', 'text' => 'We needed a complex Twilio integration and XCodrix delivered beyond expectations. Their communication systems expertise is unmatched.'],
        ['name' => 'Jena Karlis', 'role' => 'Founder, DataFlow', 'image' => 'Jena-Karlis.webp', 'text' => 'The AI chatbot XCodrix built handles 60% of our support tickets automatically. ROI was visible within the first month of launch.'],
        ['name' => 'Saul Goodman', 'role' => 'Product Lead, InnovateLab', 'image' => 'saul-goodman.webp', 'text' => 'Professional, on-time, and technically excellent. XCodrix is our go-to partner for all Laravel and Vue.js development.'],
    ],

    'faq' => [
        ['q' => 'What does XCodrix do?', 'a' => 'XCodrix is a software development agency that builds custom web applications, mobile apps, SaaS platforms, AI solutions, and communication systems. We specialize in Laravel, Vue.js, Nuxt.js, Twilio, and cloud infrastructure for startups and enterprises worldwide.'],
        ['q' => 'What technologies does XCodrix specialize in?', 'a' => 'Our core stack includes Laravel, PHP, Vue.js, Nuxt.js, React Native, Twilio, OpenAI, AWS, Docker, PostgreSQL, and Redis. We choose the right technology for each project based on your requirements, not trends.'],
        ['q' => 'How much does a project cost?', 'a' => 'Project costs vary based on scope and complexity. MVPs typically start from $15,000, while enterprise systems range from $50,000 to $200,000+. We provide detailed proposals with fixed pricing after the discovery phase.'],
        ['q' => 'How long does a typical project take?', 'a' => 'An MVP takes 8–12 weeks. Full-featured SaaS platforms take 4–6 months. We provide detailed timelines during the proposal phase and deliver on schedule with weekly progress demos.'],
        ['q' => 'Do you work with startups?', 'a' => 'Yes. Many of our clients are startups building their first product. We help with MVP strategy, technology choices, and scalable architecture so you can grow without rebuilding.'],
        ['q' => 'Do you provide ongoing support after launch?', 'a' => 'Absolutely. We offer maintenance plans, feature development retainers, and on-demand support. Most clients continue working with us long after the initial launch.'],
        ['q' => 'Can you integrate with our existing systems?', 'a' => 'Yes. We regularly integrate with CRMs, payment gateways, ERPs, Twilio, Stripe, and custom APIs. Our API-first approach ensures smooth connectivity.'],
        ['q' => 'What is your development process?', 'a' => 'We follow an agile process: Discovery → Design → Development (2-week sprints) → Testing → Launch → Support. You receive weekly demos and have direct access to the development team.'],
        ['q' => 'Do you sign NDAs?', 'a' => 'Yes. We sign NDAs before any project discussion and treat all client information as strictly confidential.'],
        ['q' => 'How do I get started?', 'a' => 'Book a free consultation through our contact page or email hello@xcodrix.com. We respond within 24 hours and provide a tailored proposal within 48 hours.'],
        ['q' => 'Where is XCodrix located?', 'a' => 'XCodrix operates as a remote-first agency serving clients worldwide. We work across time zones with flexible meeting schedules.'],
        ['q' => 'Can you help with AI integration?', 'a' => 'Yes. We build AI features including chatbots, document processing, predictive analytics, and LLM integrations using OpenAI, Claude, and custom models.'],
    ],

    'blog' => [
        ['slug' => 'why-laravel-best-saas-2026', 'title' => 'Why Laravel Is Still the Best Choice for SaaS in 2026', 'excerpt' => 'Laravel\'s ecosystem, performance improvements, and developer experience make it the top framework for building scalable SaaS products.', 'date' => '2026-06-15', 'category' => 'Laravel', 'read_time' => '5 min'],
        ['slug' => 'twilio-voice-integration-guide', 'title' => 'Building Production Twilio Voice Systems: A Complete Guide', 'excerpt' => 'Learn how to build reliable IVR systems, call routing, and voice bots with Twilio and Laravel.', 'date' => '2026-06-01', 'category' => 'Twilio', 'read_time' => '8 min'],
        ['slug' => 'ai-chatbot-business-roi', 'title' => 'How AI Chatbots Deliver 60% Support Cost Reduction', 'excerpt' => 'Real-world case study on implementing LLM-powered customer support and measuring ROI.', 'date' => '2026-05-20', 'category' => 'AI', 'read_time' => '6 min'],
        ['slug' => 'vue-nuxt-seo-best-practices', 'title' => 'Vue.js vs Nuxt.js: Choosing the Right Frontend for SEO', 'excerpt' => 'When to use SPA vs SSR for your next project and how it impacts Google rankings and AI discoverability.', 'date' => '2026-05-10', 'category' => 'Frontend', 'read_time' => '7 min'],
        ['slug' => 'mvp-development-checklist', 'title' => 'The Ultimate MVP Development Checklist for Startups', 'excerpt' => 'Everything you need to know before building your first product — from tech stack to launch strategy.', 'date' => '2026-04-28', 'category' => 'Startups', 'read_time' => '10 min'],
        ['slug' => 'laravel-api-design-patterns', 'title' => 'Laravel API Design Patterns for Scalable Applications', 'excerpt' => 'Best practices for versioning, authentication, rate limiting, and documentation in Laravel APIs.', 'date' => '2026-04-15', 'category' => 'Laravel', 'read_time' => '9 min'],
    ],

    'pages' => [
        'home' => [
            'title' => 'XCodrix — Custom Software Development Agency | AI, SaaS, Laravel & Mobile Apps',
            'description' => 'XCodrix builds AI-powered SaaS platforms, Laravel backends, Vue.js frontends, mobile apps, and Twilio communication systems. Book a free consultation with our expert development team.',
        ],
        'about' => [
            'title' => 'About XCodrix — Expert Software Development Team',
            'description' => 'Learn about XCodrix, a premium software development agency with 12+ years of experience building SaaS, AI, Laravel, and mobile solutions for startups and enterprises.',
        ],
        'services' => [
            'title' => 'Our Services — AI, SaaS, Laravel, Vue.js & More | XCodrix',
            'description' => 'Explore XCodrix services: AI development, SaaS platforms, Laravel backends, Vue.js frontends, Twilio voice systems, CRM, APIs, cloud DevOps, and mobile apps.',
        ],
        'why-choose-us' => [
            'title' => 'Why Choose XCodrix — Trusted Software Development Partner',
            'description' => 'Discover why 85+ companies trust XCodrix for software development — expert team, transparent process, on-time delivery, and long-term partnership.',
        ],
        'process' => [
            'title' => 'Our Development Process — How XCodrix Builds Software',
            'description' => 'XCodrix follows a proven 6-step development process: discovery, design, agile development, testing, launch, and ongoing support.',
        ],
        'industries' => [
            'title' => 'Industries We Serve — SaaS, Healthcare, FinTech & More | XCodrix',
            'description' => 'XCodrix serves SaaS startups, healthcare, FinTech, e-commerce, real estate, education, logistics, and telecommunications industries.',
        ],
        'portfolio' => [
            'title' => 'Portfolio & Case Studies — XCodrix Projects',
            'description' => 'View XCodrix case studies: SaaS platforms, AI chatbots, Twilio voice systems, CRM solutions, and mobile apps built for real clients.',
        ],
        'technologies' => [
            'title' => 'Technologies We Use — Laravel, Vue.js, Twilio, AWS | XCodrix',
            'description' => 'XCodrix tech stack: Laravel, PHP, Vue.js, Nuxt.js, React Native, Twilio, OpenAI, AWS, Docker, PostgreSQL, and more.',
        ],
        'testimonials' => [
            'title' => 'Client Testimonials — What Our Clients Say | XCodrix',
            'description' => 'Read testimonials from XCodrix clients who trusted us to build their SaaS platforms, AI solutions, and communication systems.',
        ],
        'faq' => [
            'title' => 'FAQ — Frequently Asked Questions | XCodrix',
            'description' => 'Answers to common questions about XCodrix services, pricing, process, technologies, and how to get started with your project.',
        ],
        'blog' => [
            'title' => 'Blog & Insights — Software Development Articles | XCodrix',
            'description' => 'Expert articles on Laravel, Vue.js, AI, Twilio, SaaS development, and startup MVP strategy from the XCodrix team.',
        ],
        'contact' => [
            'title' => 'Contact XCodrix — Book a Free Consultation',
            'description' => 'Get in touch with XCodrix for a free project consultation. We respond within 24 hours with a tailored proposal.',
        ],
    ],
];
